import pygame
import sys
import time
import subprocess
import os
from pygame.locals import *
from DefFrontEndEmuMapFile import *
from DefFrontEndEmuFile import *
from ConfAllPath import *
from DefFrontEndGameMapFile import DefFrontEndGameMap
from DefLaunchSomethingFile import DefLaunchSomething
from DefDownladPerGame import DownloadGraphical
from DefCheckEnvFile import DefCheckEnv



def Transition(Resolution,emu,MapingEmu,li,CptEmu,MAX_EMU,MAX,Orientation):
        PyrScreen =   pygame.display.set_mode(Resolution,FULLSCREEN)
	pygame.mixer.quit()
	movie = pygame.movie.Movie('MEDIA/boom.mpg')
	movie.set_volume(0.8)

	#VIDE FULLSCREEN
	mrect = pygame.Rect((0,0),Resolution)

	#mrect = pygame.Rect(WHERE_SNAP,SIZE_SNAP_CONVERT)
	movie.set_display(PyrScreen,mrect)
	movie.play()
	while movie.get_busy():
		evt = pygame.event.wait()
		if any( [  evt.type == JOYAXISMOTION,evt.type == JOYBUTTONDOWN, evt.type == QUIT,evt.type == KEYDOWN] ):
			T1=0
			T2=0
			movie.stop()
			movie=None
			pygame.mixer.init()
			break
		pygame.display.flip()

